[2025-04-17T04:03:42.294+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zephyr_real_estate_model_dag.download_model manual__2025-04-17T03:58:22.060682+00:00 [queued]>
[2025-04-17T04:03:42.300+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zephyr_real_estate_model_dag.download_model manual__2025-04-17T03:58:22.060682+00:00 [queued]>
[2025-04-17T04:03:42.301+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 4
[2025-04-17T04:03:42.309+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): download_model> on 2025-04-17 03:58:22.060682+00:00
[2025-04-17T04:03:42.312+0000] {standard_task_runner.py:57} INFO - Started process 682 to run task
[2025-04-17T04:03:42.315+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'zephyr_real_estate_model_dag', 'download_model', 'manual__2025-04-17T03:58:22.060682+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/Download_model.py', '--cfg-path', '/tmp/tmpcy5d5hw1']
[2025-04-17T04:03:42.315+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask download_model
[2025-04-17T04:03:42.350+0000] {task_command.py:410} INFO - Running <TaskInstance: zephyr_real_estate_model_dag.download_model manual__2025-04-17T03:58:22.060682+00:00 [running]> on host 8793e6621b44
[2025-04-17T04:03:42.396+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='zephyr_real_estate_model_dag' AIRFLOW_CTX_TASK_ID='download_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T03:58:22.060682+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T03:58:22.060682+00:00'
[2025-04-17T04:03:42.397+0000] {Download_model.py:113} INFO - PyTorch patched for compatibility
[2025-04-17T04:03:42.519+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/transformers/utils/hub.py:105: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

[2025-04-17T04:03:43.949+0000] {Download_model.py:124} INFO - Downloading tokenizer: HuggingFaceH4/zephyr-7b-beta
[2025-04-17T04:03:44.211+0000] {Download_model.py:131} INFO - Downloading model: HuggingFaceH4/zephyr-7b-beta
[2025-04-17T04:03:44.927+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-17T04:03:45.148+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/torch/nn/modules/module.py:2025: UserWarning: for weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '

[2025-04-17T04:03:46.211+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:  12%|#2        | 1/8 [00:01<00:08,  1.28s/it]
[2025-04-17T04:03:46.843+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:  25%|##5       | 2/8 [00:01<00:05,  1.11it/s]
[2025-04-17T04:03:47.684+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:  38%|###7      | 3/8 [00:02<00:04,  1.15it/s]
[2025-04-17T04:03:48.304+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:  50%|#####     | 4/8 [00:03<00:03,  1.29it/s]
[2025-04-17T04:03:49.022+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:  62%|######2   | 5/8 [00:04<00:02,  1.33it/s]
[2025-04-17T04:03:49.023+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards: 100%|##########| 8/8 [00:04<00:00,  1.95it/s]
[2025-04-17T04:03:49.122+0000] {Download_model.py:151} ERROR - Error downloading model: weight is on the meta device, we need a `value` to put in on cpu.
[2025-04-17T04:03:49.126+0000] {Download_model.py:152} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/Download_model.py", line 133, in download_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/***/.local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
    return model_class.from_pretrained(
  File "/home/***/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4475, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/big_modeling.py", line 423, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 677, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 677, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 635, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 167, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 289, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device, tied_params_map=self.tied_params_map)
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 283, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: weight is on the meta device, we need a `value` to put in on cpu.

[2025-04-17T04:03:49.126+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Download_model.py", line 133, in download_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/airflow/.local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
    return model_class.from_pretrained(
  File "/home/airflow/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4475, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/big_modeling.py", line 423, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 677, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 677, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 635, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 167, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 289, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device, tied_params_map=self.tied_params_map)
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 283, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: weight is on the meta device, we need a `value` to put in on cpu.
[2025-04-17T04:03:49.131+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=zephyr_real_estate_model_dag, task_id=download_model, execution_date=20250417T035822, start_date=20250417T040342, end_date=20250417T040349
[2025-04-17T04:03:49.139+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task download_model (weight is on the meta device, we need a `value` to put in on cpu.; 682)
[2025-04-17T04:03:49.186+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-04-17T04:03:49.199+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
