[2025-04-17T03:56:10.661+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zephyr_real_estate_model_dag.download_model manual__2025-04-17T03:55:57.371315+00:00 [queued]>
[2025-04-17T03:56:10.668+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zephyr_real_estate_model_dag.download_model manual__2025-04-17T03:55:57.371315+00:00 [queued]>
[2025-04-17T03:56:10.668+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 4
[2025-04-17T03:56:10.676+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): download_model> on 2025-04-17 03:55:57.371315+00:00
[2025-04-17T03:56:10.680+0000] {standard_task_runner.py:57} INFO - Started process 512 to run task
[2025-04-17T03:56:10.683+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'zephyr_real_estate_model_dag', 'download_model', 'manual__2025-04-17T03:55:57.371315+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/Download_model.py', '--cfg-path', '/tmp/tmpz2l_iln3']
[2025-04-17T03:56:10.683+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask download_model
[2025-04-17T03:56:10.715+0000] {task_command.py:410} INFO - Running <TaskInstance: zephyr_real_estate_model_dag.download_model manual__2025-04-17T03:55:57.371315+00:00 [running]> on host 8793e6621b44
[2025-04-17T03:56:10.762+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='zephyr_real_estate_model_dag' AIRFLOW_CTX_TASK_ID='download_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T03:55:57.371315+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T03:55:57.371315+00:00'
[2025-04-17T03:56:10.763+0000] {Download_model.py:113} INFO - PyTorch patched for compatibility
[2025-04-17T03:56:10.880+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/transformers/utils/hub.py:105: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

[2025-04-17T03:56:11.941+0000] {Download_model.py:124} INFO - Downloading tokenizer: HuggingFaceH4/zephyr-7b-beta
[2025-04-17T03:56:12.267+0000] {Download_model.py:131} INFO - Downloading model: HuggingFaceH4/zephyr-7b-beta
[2025-04-17T03:56:13.387+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]
[2025-04-17T03:56:14.243+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.9/site-packages/torch/nn/modules/module.py:2025: UserWarning: for weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '

[2025-04-17T03:56:17.482+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:  12%|#2        | 1/8 [00:04<00:28,  4.09s/it]
[2025-04-17T03:56:22.866+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:  25%|##5       | 2/8 [00:09<00:29,  4.85s/it]
[2025-04-17T03:56:31.630+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:  38%|###7      | 3/8 [00:18<00:33,  6.64s/it]
[2025-04-17T03:56:35.259+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:  50%|#####     | 4/8 [00:21<00:21,  5.45s/it]
[2025-04-17T03:56:39.504+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards:  62%|######2   | 5/8 [00:26<00:15,  5.01s/it]
[2025-04-17T03:56:39.505+0000] {logging_mixin.py:149} WARNING - Loading checkpoint shards: 100%|##########| 8/8 [00:26<00:00,  3.26s/it]
[2025-04-17T03:56:39.640+0000] {Download_model.py:151} ERROR - Error downloading model: weight is on the meta device, we need a `value` to put in on cpu.
[2025-04-17T03:56:39.647+0000] {Download_model.py:152} ERROR - Traceback (most recent call last):
  File "/opt/***/dags/Download_model.py", line 133, in download_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/***/.local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
    return model_class.from_pretrained(
  File "/home/***/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4475, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/big_modeling.py", line 423, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 677, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 677, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 635, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 167, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 289, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device, tied_params_map=self.tied_params_map)
  File "/home/***/.local/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 283, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: weight is on the meta device, we need a `value` to put in on cpu.

[2025-04-17T03:56:39.647+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Download_model.py", line 133, in download_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/airflow/.local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
    return model_class.from_pretrained(
  File "/home/airflow/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 4475, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/big_modeling.py", line 423, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 677, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 677, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 635, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 167, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/hooks.py", line 289, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device, tied_params_map=self.tied_params_map)
  File "/home/airflow/.local/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 283, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: weight is on the meta device, we need a `value` to put in on cpu.
[2025-04-17T03:56:39.657+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=zephyr_real_estate_model_dag, task_id=download_model, execution_date=20250417T035557, start_date=20250417T035610, end_date=20250417T035639
[2025-04-17T03:56:39.669+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task download_model (weight is on the meta device, we need a `value` to put in on cpu.; 512)
[2025-04-17T03:56:39.714+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-04-17T03:56:39.741+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
